paths:
  uploads: assets/uploads
  data: _data
  layouts: _layouts
  includes: _includes
_inputs:
  layout:
      type: auto
      hidden: true
      cascade: true
collections_config:
  data:
    path: _data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_select_data:
  data_config:
    site-settings:
_structures: {}
_editables: {}
data_config: {}
timezone: America/Los_Angeles