seo:
  site_name: NL Healing
  title: Nance Leombruno Presents
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username:
svgs:
  down: fa-solid fa-chevron-down
  ig: fa-brands fa-instagram
  right: fa-solid fa-arrow-right-long
