seo:
  site_name: NL Healing
  title: Nance Leombruno Presents
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username:
payment_links:
  venmo: https://account.venmo.com/u/nanceleombruno
